name: "kustomize-diff"
description: "Kustomize build head and base of PR, add diff as comment"
inputs:
  event:
    description: "Event that triggered action"
    default: ${{ github.event }}
    required: false
  token:
    description: "Token for GitHub authentication"
    default: ${{ github.token }}
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
