name: "kustomize-diff"
description: "Kustomize build head and base of PR, add diff as comment"
inputs:
  event:
    description: "Event that triggered action"
    required: true
  token:
    description: "Token for GitHub authentication"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
