#!/usr/bin/env bash

set -eux

TMP_DIR="$(mktemp -d)"

function build {
  local ref="$1"
  printf "\n\nChecking out ref: %s\n" "$ref"
  git checkout "$ref" --quiet
  for envpath in kustomize/*; do
    local build_dir
    if [ "$envpath" == "kustomize/_modules" ]; then continue; fi
    build_dir="$TMP_DIR/$ref/$(basename "$envpath")"
    printf "\n\nCreating build directory: %s\n" "$build_dir"
    mkdir -p "$build_dir"
    echo "Running kustomize"
    kustomize build "$envpath" -o "$build_dir"
  done
}

function comment {
  local data url
  data="{\"body\": \"$(printf "\`\`\` diff\n%s\n\`\`\`\n" "$DIFF")\"}"
  data="${data//$'\n'/'%0A'}"
  data="${data//$"'"/'%27'}"
  url="https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$INPUT_PR_NUM/comments"
  printf "\n\nTrying to write comment to GitHub\ndata: %s\nurl: %s\n" "$data" "$url"
  curl \
    --data "$data" \
    --header "Authorization: Bearer $INPUT_TOKEN" \
    --header "Content-Type: application/json" \
    --request POST \
    --url "$url"
}

function main {
  build "$INPUT_HEAD_REF"
  build "$INPUT_BASE_REF"
  set +e
  DIFF=$(git diff --no-index "$TMP_DIR/$INPUT_BASE_REF" "$TMP_DIR/$INPUT_HEAD_REF")
  if [ "$?" == "1" ]; then
    comment
  fi
  set -e
  printf "\n\nDiff: %s\n" "$DIFF"
}

main
