#!/usr/bin/env bash

set -eu

TMP_DIR="$(mktemp -d)"

function build {
  local ref="$1"
  git checkout "$ref" --quiet
  for envpath in kustomize/*; do
    local build_dir
    if [ "$envpath" == "kustomize/_modules" ]; then continue; fi
    build_dir="$TMP_DIR/$ref/$(basename "$envpath")"
    mkdir -p "$build_dir"
    kustomize build "$envpath" -o "$build_dir"
  done
}

function comment {
  curl \
    --data "{\"body\": \"$(printf "\`\`\` diff\n%s\n\`\`\`\n" "$DIFF")\"}" \
    --header "Authorization: Bearer $INPUT_TOKEN" \
    --header "Content-Type: application/json" \
    --request POST \
    --url "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$INPUT_PR_NUM/comments"
}

function main {
  build "$INPUT_HEAD_REF"
  build "$INPUT_BASE_REF"
  DIFF=$(git diff --no-index "$TMP_DIR/$INPUT_BASE_REF" "$TMP_DIR/$INPUT_HEAD_REF")
  if [ "$?" == "1" ]; then
    comment
  fi
}

main
